spring:
  datasource:
    url: jdbc:mysql://localhost:3306/stu_database?characterEncoding=utf-8&serverTimezone=UTC
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis-plus:
  global-config:
    db-config:
      logic-delete-field: "isDeleted"
      logic-delete-value: 1
      logic-not-delete-value: 0

